version: '2'
services:
  mongo:
    image: "mongo:latest"
    expose:
    - 27017
    networks:
      - db
  mongo_client:
    image: "mongo-express:latest"
    ports:
      - "8081:8081"
    networks:
      - db
    depends_on:
      - mongo
  yl24vh_api_prod:
    build:
      context: ../../backend/
      dockerfile: ./docker/prod/Dockerfile
    ports:
     - "1337:1337"
    networks:
      - db
    depends_on:
      - mongo
  yl24vh_client_prod:
    build:
      context: ../../front/
      dockerfile: ./docker/prod/Dockerfile
    ports:
     - "80":3000"

networks:
  db:
   driver: bridge